interface ReadingOverviewProps {
      total: number;
        inProgress: number;
          finished: number;
            mostRecentTitle?: string;
            }

            export const ReadingOverview = ({
              total,
                inProgress,
                  finished,
                    mostRecentTitle,
                    }: ReadingOverviewProps) => {
                      return (
                          <div
                                style={{
                                        background: "linear-gradient(180deg, #f2f5ff, #ffffff)",
                                                borderRadius: "22px",
                                                        border: "2px solid #e5e7eb",
                                                                padding: "1.1rem 1.3rem",
                                                                        boxShadow: "0 6px 0 #e5e7eb",
                                                                                marginBottom: "1.2rem",
                                                                                      }}
                                                                                          >
                                                                                                <div
                                                                                                        style={{
                                                                                                                  fontSize: "0.75rem",
                                                                                                                            fontWeight: 700,
                                                                                                                                      color: "#6b6b6b",
                                                                                                                                                letterSpacing: "0.04em",
                                                                                                                                                          textTransform: "uppercase",
                                                                                                                                                                    marginBottom: "0.6rem",
                                                                                                                                                                            }}
                                                                                                                                                                                  >
                                                                                                                                                                                          Reading overview
                                                                                                                                                                                                </div>

                                                                                                                                                                                                      <div
                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                        display: "flex",
                                                                                                                                                                                                                                  justifyContent: "space-between",
                                                                                                                                                                                                                                            gap: "0.8rem",
                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                  <div style={{ flex: 1 }}>
                                                                                                                                                                                                                                                                            <strong
                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                      display: "block",
                                                                                                                                                                                                                                                                                                                    fontSize: "1.25rem",
                                                                                                                                                                                                                                                                                                                                  lineHeight: 1.2,
                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                    {total}
                                                                                                                                                                                                                                                                                                                                                                              </strong>
                                                                                                                                                                                                                                                                                                                                                                                        <span
                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: "0.8rem",
                                                                                                                                                                                                                                                                                                                                                                                                                                color: "#6b6b6b",
                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Books total
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ flex: 1 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <strong
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                display: "block",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontSize: "1.25rem",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            lineHeight: 1.2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {inProgress}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: "0.8rem",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: "#6b6b6b",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            In progress
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ flex: 1 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <strong
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          display: "block",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: "1.25rem",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      lineHeight: 1.2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {finished}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: "0.8rem",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: "#6b6b6b",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Finished
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {mostRecentTitle && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  marginTop: "0.6rem",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontSize: "0.8rem",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: "#6b6b6b",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Most recently read: <strong>{mostRecentTitle}</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };